stages:
  - pull
  - build
  - push
  - deploy


variables:
  PROJECT_REGISTRY_URL: registry.gitlab.propulsion-home.ch/pmavrodiev/test
  PROJECT_REGISTRY_TAG: master

before_script:
  - docker login -u $CI_REGISTRY_USER -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

pull images:
  stage: pull
  allow_failure: true
  script:
    - docker pull $PROJECT_REGISTRY_URL:$PROJECT_REGISTRY_TAG

build:
  stage: build
  script:
    - docker build -f ./build/Dockerfile -t $PROJECT_REGISTRY_URL:$PROJECT_REGISTRY_TAG .

push:
  stage: push
  only:
    - master
  script:
    - docker push $PROJECT_REGISTRY_URL:$PROJECT_REGISTRY_TAG

deploy to cloud:
  stage: deploy
  only:
    - master
    - tags
  script:
    - export PROJECT_REGISTRY_URL=$PROJECT_REGISTRY_URL
    - export PROJECT_REGISTRY_TAG=$PROJECT_REGISTRY_TAG
    - docker network create syntheticus_network || true
    - docker-compose -f ./build/docker-compose.yml -d --build up

