version: '3'
services:
  database:
    image: postgres:11.0
    restart: always
    env_file:
      - prod.env
    volumes:
      - database:/var/lib/postgresql/data

  app:
    image: registry.gitlab.propulsion-home.ch/document-annotation/backend:master
    restart: always
    env_file:
      - prod.env
    ports:
      - "9000:8000"
    depends_on:
      - database
      - elasticsearch
    command: 'sh /scripts/run.sh'
    volumes:
      - static-files:/static-files
      - media-files:/media-files

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    depends_on:
      - database

volumes:
  database:
  media-files:
    external: true
  static-files:
    external: true
  esdata1:
    driver: local

networks:
  default:
    external:
      name: jacob
