# Generated by Django 2.0.3 on 2018-12-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('color', models.CharField(max_length=7, verbose_name='color')),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tags.DocumentTags', verbose_name='parent_tag')),
            ],
        ),
        migrations.CreateModel(
            name='HighlightedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField(blank=True, verbose_name='selected_text')),
                ('all_doc_tagged', models.BooleanField(default=False, verbose_name='all_doc_tagged')),
                ('start_of_selection', models.IntegerField(blank=True, null=True, verbose_name='start_of_selection')),
                ('document_tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlighted_text', to='tags.DocumentTags', verbose_name='document_tags')),
            ],
        ),
        migrations.CreateModel(
            name='PdfDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(null=True, upload_to='./pdfs')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(null=True, verbose_name='text')),
                ('html_text', models.TextField(null=True, verbose_name='html_text')),
                ('html_created', models.BooleanField(default=False, verbose_name='html_created')),
                ('text_created', models.BooleanField(default=False, verbose_name='html_created')),
                ('html_text_created', models.BooleanField(default=False, verbose_name='html_text_created')),
            ],
        ),
        migrations.AddField(
            model_name='highlightedtext',
            name='pdf_documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlighted_text', to='tags.PdfDocuments', verbose_name='pdf_documents'),
        ),
        migrations.AddField(
            model_name='documenttags',
            name='pdf_documents',
            field=models.ManyToManyField(blank=True, related_name='document_tags', to='tags.PdfDocuments', verbose_name='pdf_documents'),
        ),
    ]
