stages:
  - pull
  - build
  - push
  - deploy
  - cleanup

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

pull:
  stage: pull
  allow_failure: true
  script:
    - docker pull "$CI_REGISTRY_IMAGE":latest

build:
  stage: build
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE":"$CI_BUILD_REF_NAME" .

push tags:
  stage: push
  when: on_success
  only:
    - tags
    - master
  script:
    - docker push "$CI_REGISTRY_IMAGE":"$CI_BUILD_REF_NAME"

push latest:
  stage: push
  script:
    - docker tag "$CI_REGISTRY_IMAGE":"$CI_BUILD_REF_NAME" "$CI_REGISTRY_IMAGE":latest
    - docker push "$CI_REGISTRY_IMAGE":latest

cleanup:
  stage: cleanup
  when: always
  script:
    - docker rmi -f "$CI_PIPELINE_ID":"$CI_BUILD_REF_NAME"

deploy:
  when: manual
  stage: deploy
  environment:
    name: prod
  only:
  - master
  - tags
  variables:
    ENVIRONMENT: "prod"
  script:
    - echo "deploying version $(git describe --always --tags) to $HOST"

    - echo "create volumes and network for very first deployment"
    - docker network create jacob || true
    - docker volume create --name=frontend || true
    - docker volume create --name=static-files || true
    - docker volume create --name=media-files || true

    - echo "update/restart"
    - docker-compose -f docker-compose.deploy.yml pull
    - docker-compose -f docker-compose.deploy.yml down --remove-orphans
    - docker-compose -f docker-compose.deploy.yml up -d
