version: '3'
services:
  nginx:
    image: registry.gitlab.propulsion-home.ch/document-annotation/nginx:latest
    restart: always
    command: "sh /start.sh"
    ports:
      - "9000:80"
      - "443:443"
    volumes:
      - media-files:/media-files
      - static-files:/static-files
      - ./config:/etc/nginx/conf.d

volumes:
  frontend:
  media-files:
  static-files:
